/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasdatafilm;

import Koneksi.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author WINDOWS 11
 */
public class FormTambahStudio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTambahStudio.class.getName());

    /**
     * Creates new form FormTambahGenre
     */
    public FormTambahStudio() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        PlaceholderSupport.install(jTextFieldCARI, "Cari nama studio");
        PlaceholderSupport.install(jTextFieldGENRE, "Masukkan nama studio");
        loadDataStudio();
        jButtonCARI.addActionListener(e -> cariDataStudio());
        jButtonTAMBAH.addActionListener(e -> tambahStudio());
        jButtonHAPUS.addActionListener(e -> hapusStudio());
        jButtonKEMBALI.addActionListener(e -> {
            dispose();
            new FormFilmAdmin().setVisible(true);
        });
        jTableGENRE.getSelectionModel().addListSelectionListener(event -> {
            if (!event.getValueIsAdjusting() && jTableGENRE.getSelectedRow() != -1) {
                int row = jTableGENRE.getSelectedRow();
                PlaceholderSupport.setText(jTextFieldGENRE, jTableGENRE.getValueAt(row, 1).toString());
            }
        });
        AdminMenuBar.buat(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCARI = new javax.swing.JTextField();
        jTextFieldGENRE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonTAMBAH = new javax.swing.JButton();
        jButtonCARI = new javax.swing.JButton();
        jButtonHAPUS = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGENRE = new javax.swing.JTable();
        jButtonKEMBALI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DATA STUDIO");

        jLabel3.setText("Nama Studio Baru     :");

        jTextFieldCARI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCARIActionPerformed(evt);
            }
        });

        jTextFieldGENRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGENREActionPerformed(evt);
            }
        });

        jLabel2.setText("Cari Studio:");

        jButtonTAMBAH.setText("TAMBAH");
        jButtonTAMBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTAMBAHActionPerformed(evt);
            }
        });

        jButtonCARI.setText("Cari");

        jButtonHAPUS.setText("HAPUS");
        jButtonHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHAPUSActionPerformed(evt);
            }
        });

        jTableGENRE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nama Studio"
            }
        ));
        jScrollPane1.setViewportView(jTableGENRE);

        jButtonKEMBALI.setText("KEMBALI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)
                                    .addComponent(jTextFieldGENRE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jButtonTAMBAH)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonHAPUS))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldCARI, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonCARI, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 7, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonKEMBALI)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldGENRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTAMBAH)
                    .addComponent(jButtonHAPUS))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCARI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCARI))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButtonKEMBALI)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCARIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCARIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCARIActionPerformed

    private void jTextFieldGENREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGENREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGENREActionPerformed

    private void jButtonTAMBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTAMBAHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTAMBAHActionPerformed

    private void jButtonHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHAPUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHAPUSActionPerformed

    private void loadDataStudio() {
        DefaultTableModel model = modelStudioKosong();
        try (Connection conn = Koneksi.getConnection();
             PreparedStatement stmt = conn.prepareStatement("SELECT id_studio, nama_studio FROM studio ORDER BY id_studio ASC");
             ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt("id_studio"), rs.getString("nama_studio")});
            }
            jTableGENRE.setModel(model);
        } catch (SQLException ex) {
            tampilkanErrorDatabase("Data studio gagal dimuat.", ex);
        }
    }

    private DefaultTableModel modelStudioKosong() {
        return new DefaultTableModel(new String[]{"ID", "Nama Studio"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
    }

    private void tampilkanErrorDatabase(String pesan, SQLException exception) {
        logger.log(java.util.logging.Level.SEVERE, pesan, exception);
        JOptionPane.showMessageDialog(this, pesan + " Periksa koneksi database.",
                "Kesalahan database", JOptionPane.ERROR_MESSAGE);
    }

    private void cariDataStudio() {
        String keyword = PlaceholderSupport.getText(jTextFieldCARI).trim();
        DefaultTableModel model = modelStudioKosong();
        try (Connection conn = Koneksi.getConnection();
             PreparedStatement stmt = conn.prepareStatement("SELECT id_studio, nama_studio FROM studio WHERE nama_studio LIKE ? ORDER BY id_studio ASC")) {

            stmt.setString(1, "%" + keyword + "%");
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getInt("id_studio"), rs.getString("nama_studio")});
                }
            }
            jTableGENRE.setModel(model);
        } catch (SQLException ex) {
            tampilkanErrorDatabase("Pencarian studio gagal.", ex);
        }
    }

    private void tambahStudio() {
        String namaStudio = PlaceholderSupport.getText(jTextFieldGENRE).trim();
        if (namaStudio.isEmpty() || namaStudio.length() > 30) {
            JOptionPane.showMessageDialog(this, "Nama studio wajib diisi dan maksimal 30 karakter.");
            return;
        }

        try (Connection conn = Koneksi.getConnection();
             PreparedStatement stmt = conn.prepareStatement("INSERT INTO studio (nama_studio) VALUES (?)")) {
            stmt.setString(1, namaStudio);
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data studio berhasil ditambahkan.");
            PlaceholderSupport.reset(jTextFieldGENRE);
            loadDataStudio();
        } catch (SQLException ex) {
            String pesan = "23000".equals(ex.getSQLState())
                    ? "Nama studio tersebut sudah digunakan." : "Studio gagal ditambahkan.";
            tampilkanErrorDatabase(pesan, ex);
        }
    }

    private void hapusStudio() {
        int selectedRow = jTableGENRE.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih studio yang ingin dihapus pada tabel terlebih dahulu.");
            return;
        }

        int id = (int) jTableGENRE.getValueAt(selectedRow, 0);
        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus studio ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try (Connection conn = Koneksi.getConnection();
                 PreparedStatement stmt = conn.prepareStatement("DELETE FROM studio WHERE id_studio = ?")) {
                stmt.setInt(1, id);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data studio berhasil dihapus.");
                PlaceholderSupport.reset(jTextFieldGENRE);
                loadDataStudio();
            } catch (SQLIntegrityConstraintViolationException ex) {
                JOptionPane.showMessageDialog(this,
                        "Studio tidak dapat dihapus karena masih digunakan jadwal tayang.");
            } catch (SQLException ex) {
                tampilkanErrorDatabase("Studio gagal dihapus.", ex);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormTambahStudio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCARI;
    private javax.swing.JButton jButtonHAPUS;
    private javax.swing.JButton jButtonKEMBALI;
    private javax.swing.JButton jButtonTAMBAH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableGENRE;
    private javax.swing.JTextField jTextFieldCARI;
    private javax.swing.JTextField jTextFieldGENRE;
    // End of variables declaration//GEN-END:variables
}
